name: mk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  http: ^0.13.4
  json_serializable: ^6.1.4
  google_maps_flutter: ^2.1.1
  connectivity_plus: ^2.2.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  google_sign_in: ^5.2.3
  font_awesome_flutter: ^9.2.0
  location: ^4.3.0
  firebase_core: ^1.12.0
  pin_code_fields: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.4
  build_runner: ^2.1.7


flutter:


  generate: true
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/icons/
    - assets/locations.json

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
